/**
 * Coaching text is generated by an LLM, which may still talk about pace (or
 * quote WPM targets) when the session's pace could not be verified. The UI
 * shows "Pace: not available" in that case, so pace advice beside it would
 * contradict the evidence. This guard removes pace claims at read time without
 * altering the persisted insight, so they return if pace is later verified.
 */

export const PACE_UNSCORED_NOTE =
  'Pace was not scored for this recording because verified word timing was unavailable.'

const PACE_CLAIM =
  /\b(wpm|words?[- ]per[- ]minute|pac(?:e|es|ed|ing)|tempo|speaking (?:speed|rate)|speech rate|rush(?:ed|es|ing)?|slow(?:ing)? down|speed(?:ing)? up|(?:speak|talk)(?:ing)? (?:too |a bit |slightly |more |a little )?(?:fast|quickly|slow|slowly|faster|slower))\b/i

const TEXT_FIELDS = [
  'topStrength',
  'primaryImprovement',
  'actionableAdvice',
  'practiceExercise',
  'overallNarrative',
] as const

const PACE_SOURCES = new Set(['word_timestamps', 'validated_turn_audio'])

export function hasPaceClaim(text: string): boolean {
  return PACE_CLAIM.test(text)
}

/** Mirrors the web `hasAvailablePace` contract for persisted processing status. */
export function isPersistedPaceAvailable(processingStatus: unknown): boolean {
  if (!processingStatus || typeof processingStatus !== 'object' || Array.isArray(processingStatus)) {
    return false
  }
  const pace = (processingStatus as Record<string, unknown>).pace
  if (!pace || typeof pace !== 'object' || Array.isArray(pace)) return false
  const value = pace as Record<string, unknown>
  return (
    value.status === 'available' &&
    typeof value.source === 'string' &&
    PACE_SOURCES.has(value.source) &&
    value.confidence !== 'low'
  )
}

function stripPaceSentences(text: string): { text: string; removed: boolean } {
  const sentences = text.split(/(?<=[.!?])\s+/)
  const kept = sentences.filter((sentence) => !hasPaceClaim(sentence))
  return { text: kept.join(' ').trim(), removed: kept.length !== sentences.length }
}

export function guardPaceClaims<T>(insights: T, paceAvailable: boolean): T {
  if (paceAvailable || !insights || typeof insights !== 'object' || Array.isArray(insights)) {
    return insights
  }
  const source = insights as Record<string, unknown>
  const next: Record<string, unknown> = { ...source }
  let removed = false

  for (const field of TEXT_FIELDS) {
    const value = source[field]
    if (typeof value !== 'string' || !hasPaceClaim(value)) continue
    removed = true
    const stripped = stripPaceSentences(value).text
    if (stripped) next[field] = stripped
    else delete next[field]
  }

  if (Array.isArray(source.practicePlan)) {
    const plan = source.practicePlan.filter((item) => {
      if (!item || typeof item !== 'object') return true
      const entry = item as Record<string, unknown>
      const text = [entry.title, entry.description, entry.focusSkill]
        .filter((part): part is string => typeof part === 'string')
        .join(' ')
      return !hasPaceClaim(text)
    })
    if (plan.length !== source.practicePlan.length) {
      removed = true
      next.practicePlan = plan
    }
  }

  if (removed) next.paceNote = PACE_UNSCORED_NOTE
  return next as T
}
