import { InterviewQuestionSource } from '@prisma/client'
import { prisma } from './prisma'

const JD_CHARS = 3_500
const RESUME_CHARS = 3_500
const INTERVIEWER_CHARS = 1_200
const QUESTION_CHARS = 400
const QUESTION_COUNT = 8
const COMPANY_CHARS = 120
const ROLE_CHARS = 160
const STAGE_CHARS = 120
const LABEL_CHARS = 120
const INTERVIEWER_NAME_CHARS = 160
const INTERVIEWER_ROLE_CHARS = 160
const PRACTICE_HEADLINE_CHARS = 140
const PRACTICE_SUMMARY_CHARS = 520
const EARLIER_PRACTICE_COUNT = 4
const RECORDING_SUMMARY_CHARS = 520
const PRACTICE_QUESTION_CHARS = 320
const PRACTICE_QUESTION_COUNT = 10

// Only questions the user says were really asked. PRACTICE and AI_SUGGESTED are
// generated by us, so replaying them back as "what they asked" would be a lie.
const REAL_QUESTION_SOURCES: InterviewQuestionSource[] = [
  InterviewQuestionSource.ACTUAL_INTERVIEW,
  InterviewQuestionSource.USER_ENTERED,
]

export const MAX_PREPARE_CONTEXT_SOURCE_CHARS =
  JD_CHARS +
  RESUME_CHARS +
  INTERVIEWER_CHARS +
  QUESTION_CHARS * QUESTION_COUNT +
  COMPANY_CHARS +
  ROLE_CHARS +
  STAGE_CHARS +
  LABEL_CHARS +
  INTERVIEWER_NAME_CHARS +
  INTERVIEWER_ROLE_CHARS

function excerpt(value: string | null | undefined, max: number) {
  const normalized = value?.replace(/\s+/g, ' ').trim() || ''
  return {
    text: normalized ? normalized.slice(0, max) : null,
    truncated: normalized.length > max,
  }
}

function questionsFromAssistantTurns(turns: Array<{ text: string }>): string[] {
  const questions: string[] = []
  const seen = new Set<string>()
  for (const turn of turns) {
    // Preserve only direct prompts from the prior practice. Assistant turns
    // can also contain greetings and feedback, neither of which helps avoid
    // repeating interview questions in the next practice.
    const matches = turn.text.replace(/\s+/g, ' ').match(/[^?]{8,}\?/g) ?? []
    for (const match of matches) {
      const question = excerpt(match.trim(), PRACTICE_QUESTION_CHARS).text
      if (!question) continue
      const key = question.toLocaleLowerCase()
      if (!seen.has(key)) {
        seen.add(key)
        questions.push(question)
      }
      if (questions.length >= PRACTICE_QUESTION_COUNT) return questions
    }
  }
  return questions
}

export async function buildPrepareJourneyContext(
  sessionId: string,
  expectedUserId: string,
) {
  const link = await prisma.preparationPractice.findUnique({
    where: { sessionId },
    select: {
      preparationId: true,
      stageId: true,
      preparation: {
        select: {
          userId: true,
          interview: {
            select: {
              companyName: true,
              roleTitle: true,
              jobDescriptionText: true,
              resumeLabel: true,
              resumeText: true,
            },
          },
        },
      },
      stage: {
        select: {
          name: true,
          type: true,
          sequence: true,
          interviewerName: true,
          interviewerRole: true,
          interviewerProfileText: true,
        },
      },
    },
  })

  if (!link || link.preparation.userId !== expectedUserId || !link.preparation.interview) {
    return null
  }

  const questionScope = link.stage
    ? {
        stage: { sequence: { lte: link.stage.sequence } },
      }
    : {}
  const questions = await prisma.interviewQuestion.findMany({
    where: {
      preparationId: link.preparationId,
      source: { in: REAL_QUESTION_SOURCES },
      ...questionScope,
    },
    orderBy: [{ askedAt: 'desc' }, { createdAt: 'desc' }],
    take: QUESTION_COUNT,
    select: {
      questionText: true,
      stage: { select: { name: true } },
    },
  })

  // A Prepare practice is deliberately scoped to this one journey.  Do not
  // substitute the generic Elevate "last practice" lookup here: that lookup
  // is user/focus based and could join two unrelated interview processes.
  const priorPractices = (await prisma.preparationPractice.findMany({
    where: {
      preparationId: link.preparationId,
      sessionId: { not: sessionId },
      session: { endedAt: { not: null }, discardedAt: null },
    },
    orderBy: { createdAt: 'desc' },
    take: EARLIER_PRACTICE_COUNT + 1,
    select: {
      createdAt: true,
      stage: { select: { name: true } },
      session: {
        select: {
          sessionName: true,
          focusArea: true,
          startedAt: true,
          endedAt: true,
          durationSec: true,
          turns: {
            where: { role: 'assistant' },
            orderBy: { sequenceNo: 'desc' },
            take: PRACTICE_QUESTION_COUNT,
            select: { text: true },
          },
          metrics: { select: { coachingInsights: true, skillScores: true } },
        },
      },
    },
  })) ?? []

  const compactPractice = (practice: (typeof priorPractices)[number]) => {
    const insights = practice.session.metrics?.coachingInsights as Record<string, unknown> | null
    const headline = excerpt(
      practice.session.sessionName || practice.stage?.name || 'Practice session',
      PRACTICE_HEADLINE_CHARS,
    ).text
    const strength = excerpt(
      typeof insights?.topStrength === 'string' ? insights.topStrength : null,
      PRACTICE_SUMMARY_CHARS,
    ).text
    const improvement = excerpt(
      typeof insights?.primaryImprovement === 'string' ? insights.primaryImprovement : null,
      PRACTICE_SUMMARY_CHARS,
    ).text
    return {
      headline: headline || 'Practice session',
      stageName: practice.stage?.name ?? null,
      focusArea: practice.session.focusArea ?? null,
      completedAt: practice.session.endedAt,
      durationSec: practice.session.durationSec ?? null,
      topStrength: strength,
      primaryImprovement: improvement,
    }
  }
  const latestPractice = priorPractices[0] ? compactPractice(priorPractices[0]) : null
  const recentPracticeQuestions = questionsFromAssistantTurns(
    priorPractices.flatMap((practice) => [...practice.session.turns].reverse()),
  )
  const earlierPracticeSummary = priorPractices
    .slice(1)
    .map(compactPractice)
    .map((practice) => {
      const details = [practice.stageName, practice.topStrength, practice.primaryImprovement]
        .filter((value): value is string => Boolean(value))
        .join(' · ')
      return details ? `${practice.headline}: ${details}` : practice.headline
    })
    .join('\n')

  const priorRecordings = (await prisma.preparationRecording.findMany({
    where: {
      preparationId: link.preparationId,
      replaySession: { status: 'completed' },
    },
    orderBy: { createdAt: 'desc' },
    take: EARLIER_PRACTICE_COUNT,
    select: {
      stage: { select: { name: true } },
      replaySession: {
        select: {
          sessionName: true,
          meetingDate: true,
          result: { select: { strengths: true, improvements: true } },
        },
      },
    },
  })) ?? []
  const recordingMemory = priorRecordings.map((recording) => {
    const result = recording.replaySession.result
    const firstStrength = Array.isArray(result?.strengths)
      ? result!.strengths[0]
      : null
    const firstImprovement = Array.isArray(result?.improvements)
      ? result!.improvements[0]
      : null
    const strength = excerpt(
      firstStrength && typeof firstStrength === 'object' && 'point' in firstStrength && typeof firstStrength.point === 'string'
        ? firstStrength.point
        : null,
      RECORDING_SUMMARY_CHARS,
    ).text
    const improvement = excerpt(
      firstImprovement && typeof firstImprovement === 'object' && 'point' in firstImprovement && typeof firstImprovement.point === 'string'
        ? firstImprovement.point
        : null,
      RECORDING_SUMMARY_CHARS,
    ).text
    return {
      headline: excerpt(
        recording.replaySession.sessionName || recording.stage?.name || 'Interview recording',
        PRACTICE_HEADLINE_CHARS,
      ).text || 'Interview recording',
      stageName: recording.stage?.name ?? null,
      recordedAt: recording.replaySession.meetingDate,
      topStrength: strength,
      primaryImprovement: improvement,
    }
  })

  const interview = link.preparation.interview
  const jd = excerpt(interview.jobDescriptionText, JD_CHARS)
  const resume = excerpt(interview.resumeText, RESUME_CHARS)
  const interviewer = excerpt(link.stage?.interviewerProfileText, INTERVIEWER_CHARS)
  const company = excerpt(interview.companyName, COMPANY_CHARS)
  const role = excerpt(interview.roleTitle, ROLE_CHARS)
  const stageName = excerpt(link.stage?.name, STAGE_CHARS)
  const resumeLabel = excerpt(interview.resumeLabel, LABEL_CHARS)
  const interviewerName = excerpt(link.stage?.interviewerName, INTERVIEWER_NAME_CHARS)
  const interviewerRole = excerpt(link.stage?.interviewerRole, INTERVIEWER_ROLE_CHARS)

  return {
    preparationId: link.preparationId,
    stageId: link.stageId,
    companyName: company.text!,
    roleTitle: role.text!,
    stageName: stageName.text,
    stageType: link.stage?.type ?? null,
    jobDescriptionExcerpt: jd.text,
    jobDescriptionTruncated: jd.truncated,
    resumeLabel: resumeLabel.text,
    resumeExcerpt: resume.text,
    resumeTruncated: resume.truncated,
    interviewer: link.stage
      ? {
          name: interviewerName.text,
          role: interviewerRole.text,
          professionalContextExcerpt: interviewer.text,
          professionalContextTruncated: interviewer.truncated,
        }
      : null,
    actualQuestions: questions.map((question) => {
      const clipped = excerpt(question.questionText, QUESTION_CHARS)
      return {
        stageName: question.stage?.name ?? null,
        questionText: clipped.text ?? '',
        truncated: clipped.truncated,
      }
    }),
    practiceMemory: {
      latestPractice,
      recentPracticeQuestions,
      earlierPracticeSummary: earlierPracticeSummary || null,
      completedPracticeCount: priorPractices.length,
      recordingSummary: recordingMemory
        .map((recording) => [recording.headline, recording.stageName, recording.topStrength, recording.primaryImprovement]
          .filter((value): value is string => Boolean(value)).join(' · '))
        .join('\n') || null,
      completedRecordingCount: recordingMemory.length,
    },
  }
}
