import { InterviewQuestionSource } from '@prisma/client'
import { prisma } from './prisma'

const JD_CHARS = 3_500
const RESUME_CHARS = 3_500
const INTERVIEWER_CHARS = 1_200
const QUESTION_CHARS = 400
const QUESTION_COUNT = 8
const COMPANY_CHARS = 120
const ROLE_CHARS = 160
const STAGE_CHARS = 120
const LABEL_CHARS = 120
const INTERVIEWER_NAME_CHARS = 160
const INTERVIEWER_ROLE_CHARS = 160

// Only questions the user says were really asked. PRACTICE and AI_SUGGESTED are
// generated by us, so replaying them back as "what they asked" would be a lie.
const REAL_QUESTION_SOURCES: InterviewQuestionSource[] = [
  InterviewQuestionSource.ACTUAL_INTERVIEW,
  InterviewQuestionSource.USER_ENTERED,
]

export const MAX_PREPARE_CONTEXT_SOURCE_CHARS =
  JD_CHARS +
  RESUME_CHARS +
  INTERVIEWER_CHARS +
  QUESTION_CHARS * QUESTION_COUNT +
  COMPANY_CHARS +
  ROLE_CHARS +
  STAGE_CHARS +
  LABEL_CHARS +
  INTERVIEWER_NAME_CHARS +
  INTERVIEWER_ROLE_CHARS

function excerpt(value: string | null | undefined, max: number) {
  const normalized = value?.replace(/\s+/g, ' ').trim() || ''
  return {
    text: normalized ? normalized.slice(0, max) : null,
    truncated: normalized.length > max,
  }
}

export async function buildPrepareJourneyContext(
  sessionId: string,
  expectedUserId: string,
) {
  const link = await prisma.preparationPractice.findUnique({
    where: { sessionId },
    select: {
      preparationId: true,
      stageId: true,
      preparation: {
        select: {
          userId: true,
          interview: {
            select: {
              companyName: true,
              roleTitle: true,
              jobDescriptionText: true,
              resumeLabel: true,
              resumeText: true,
            },
          },
        },
      },
      stage: {
        select: {
          name: true,
          type: true,
          sequence: true,
          interviewerName: true,
          interviewerRole: true,
          interviewerProfileText: true,
        },
      },
    },
  })

  if (!link || link.preparation.userId !== expectedUserId || !link.preparation.interview) {
    return null
  }

  const questionScope = link.stage
    ? {
        stage: { sequence: { lte: link.stage.sequence } },
      }
    : {}
  const questions = await prisma.interviewQuestion.findMany({
    where: {
      preparationId: link.preparationId,
      source: { in: REAL_QUESTION_SOURCES },
      ...questionScope,
    },
    orderBy: [{ askedAt: 'desc' }, { createdAt: 'desc' }],
    take: QUESTION_COUNT,
    select: {
      questionText: true,
      stage: { select: { name: true } },
    },
  })

  const interview = link.preparation.interview
  const jd = excerpt(interview.jobDescriptionText, JD_CHARS)
  const resume = excerpt(interview.resumeText, RESUME_CHARS)
  const interviewer = excerpt(link.stage?.interviewerProfileText, INTERVIEWER_CHARS)
  const company = excerpt(interview.companyName, COMPANY_CHARS)
  const role = excerpt(interview.roleTitle, ROLE_CHARS)
  const stageName = excerpt(link.stage?.name, STAGE_CHARS)
  const resumeLabel = excerpt(interview.resumeLabel, LABEL_CHARS)
  const interviewerName = excerpt(link.stage?.interviewerName, INTERVIEWER_NAME_CHARS)
  const interviewerRole = excerpt(link.stage?.interviewerRole, INTERVIEWER_ROLE_CHARS)

  return {
    preparationId: link.preparationId,
    stageId: link.stageId,
    companyName: company.text!,
    roleTitle: role.text!,
    stageName: stageName.text,
    stageType: link.stage?.type ?? null,
    jobDescriptionExcerpt: jd.text,
    jobDescriptionTruncated: jd.truncated,
    resumeLabel: resumeLabel.text,
    resumeExcerpt: resume.text,
    resumeTruncated: resume.truncated,
    interviewer: link.stage
      ? {
          name: interviewerName.text,
          role: interviewerRole.text,
          professionalContextExcerpt: interviewer.text,
          professionalContextTruncated: interviewer.truncated,
        }
      : null,
    actualQuestions: questions.map((question) => {
      const clipped = excerpt(question.questionText, QUESTION_CHARS)
      return {
        stageName: question.stage?.name ?? null,
        questionText: clipped.text ?? '',
        truncated: clipped.truncated,
      }
    }),
  }
}
